#' Do a model search
#'
#' \lifecycle{experimental}
#'
#' Perform a model search \insertCite{Hair2016;textual}{cSEM}
#'
#' @usage doModelSearch(.object = NULL)
#'
#' @return The matrix and the fitness generated by the AGAS-PLS runs
#' @inheritParams csem_arguments
#' @seealso [cSEMResults]
#' @references \insertAllCited{}
#' @export
doModelSearch <- function(.object = NULL, 
                          .n_exogenous = 3,
                          .popsize = 20, 
                          .maxiter= 20,
                          .mutation_prob = 0.5,
                          .cross_prob = 0.8,
                          .seed = 1, 
                          .only_structural = FALSE) {
  if(.object$Information$Model$model_type != 'Linear'){
    stop2('Currently, `doModelSearch()` supports only linear models.')
  }
  
  if(.object$Information$Arguments$.approach_weights != "PLS-PM"){
    stop2("Currently, `doModelSearch()` supports only PLS-PM.")
  }
  
  if (!requireNamespace("GA", quietly = TRUE)) {
    stop2(
      "Package `GA` required. Use `install.packages(\"GA\")` and rerun.")
  }
  
  # Retrieve information on the model (number variables, name variables)
  .variables <- rownames(.object$Information$Model$measurement)
  .n_variables <- length(.variables)
  .measurement_model <- lapply(seq(1,nrow(.object$Information$Model$measurement)),
                               function(x){colnames(.object$Information$Model$measurement)[.object$Information$Model$measurement[x,]==1]})
  names(.measurement_model) <- rownames(.object$Information$Model$measurement)
  
  model_criteria <- calculateModelSelectionCriteria(
    .object,
    .by_equation = FALSE,
    .only_structural = .only_structural,
    .ms_criterion = 'bic'
  )
  
  BIC = model_criteria$BIC
  print(BIC)
  
  .agas_dataset <- .object$Information$Data
  
  ga_control <- GA::ga(
      type = "binary",
      nBits = .n_variables * .n_variables,
      popSize = .popsize,
      maxiter = .maxiter,
      pmutation = 1.0,
      pcrossover = .cross_prob,
      fitness = function(x) .agas_fitness(x, .agas_dataset, .n_exogenous, .measurement_model, .variables, .only_structural),
      elitism = TRUE,
      parallel = FALSE,
      seed = .seed,
      mutation = function(object, parent) .agas_mutation(object, parent, .n_variables, .mutation_prob, .n_exogenous),
      keepBest = TRUE
    )
  best <- unlist(ga_control@bestSol[.maxiter])
  best_matrix <- matrix(best, nrow = .n_variables, ncol = .n_variables, byrow = TRUE)
  
  rownames(best_matrix) <- .variables
  colnames(best_matrix) <- .variables
  
  best_fitness <- - ga_control@fitnessValue
  
  return(list(
    best_matrix  = best_matrix,
    best_fitness = best_fitness
  ))
  
}
